<?php $frontData = $block->getFrontData() ?>
<div id="frontdata-component" data-bind="scope: 'frontdatacomponent'">
Orders List
<div>
<?php foreach ( $frontData as $key => $value): ?>
    <label>Name : </label>
    <label><?php echo $value->getName(); ?></label>
    <br>
    <label>Email : </label>
    <label><?php echo $value->getEmail(); ?></label>
    <br>
    <label>Mobile : </label>
    <label><?php echo $value->getMobile(); ?></label>
    <br><br>
<?php endforeach ?>
</div>
</div>
 
<script type="text/x-magento-init">
        {
            "#frontdata-component": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "frontdatacomponent": {
                            "component": "Order_FrontController/js/frontdatacomponent",
                            "template" : "Order_FrontController/frontdata"
                        }
                    }
                }
            }
        }
</script>